services:
  state-db:
    image: "redis:alpine"
    command: redis-server --requirepass ${STATE_DB_PASSWORD}
    networks:
      - botnet
    ports:
      - 6379:6379
    environment:
      - REDIS_REPLICATION_MODE=master

  main-container:
    image: ${DOCKER_USERNAME}/multibot-main
    restart: unless-stopped
    networks:
      - botnet
    ports:
      - 8000:80
    environment:
      - BASE_URL=${BASE_URL}
      - TWITCH_SUPER_ADMIN_USERNAME=${TWITCH_SUPER_ADMIN_USERNAME}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_SECRET=${TWITCH_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - STATE_DB_URL=${STATE_DB_URL}
      - STATE_DB_PASSWORD=${STATE_DB_PASSWORD}
      - PROXY_OVERRIDES={"jjvanvan":"http://tenant-container-jjvanvan:80","minecraft1167890":"http://tenant-container-minecraft1167890:80"}

  tenant-container-jjvanvan:
    image: ${DOCKER_USERNAME}/multibot-tenant
    restart: unless-stopped
    networks:
      - botnet
    environment:
      - TWITCH_CHANNEL=jjvanvan
      - TWITCH_BOT_USERNAME=${TWITCH_BOT_USERNAME}
      - TWITCH_BOT_OAUTH_TOKEN=${TWITCH_BOT_OAUTH_TOKEN}

      - BASE_URL=${BASE_URL}
      - TWITCH_SUPER_ADMIN_USERNAME=${TWITCH_SUPER_ADMIN_USERNAME}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_SECRET=${TWITCH_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - STATE_DB_URL=${STATE_DB_URL}
      - STATE_DB_PASSWORD=${STATE_DB_PASSWORD}

  tenant-container-minecraft1167890:
    image: ${DOCKER_USERNAME}/multibot-tenant
    restart: unless-stopped
    networks:
      - botnet
    environment:
      - TWITCH_CHANNEL=minecraft1167890
      - TWITCH_BOT_USERNAME=${TWITCH_BOT_USERNAME}
      - TWITCH_BOT_OAUTH_TOKEN=${TWITCH_BOT_OAUTH_TOKEN}

      - BASE_URL=${BASE_URL}
      - TWITCH_SUPER_ADMIN_USERNAME=${TWITCH_SUPER_ADMIN_USERNAME}
      - TWITCH_CLIENT_ID=${TWITCH_CLIENT_ID}
      - TWITCH_SECRET=${TWITCH_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - STATE_DB_URL=${STATE_DB_URL}
      - STATE_DB_PASSWORD=${STATE_DB_PASSWORD}

# docker network create botnet
networks:
  botnet:
    external: true
