apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: multibot
  name: tenant-container-{{CHANNEL}}
  labels:
    app: tenant-container-{{CHANNEL}}
    group: tenant-containers
    logging: my_group
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tenant-container-{{CHANNEL}}
  template:
    metadata:
      labels:
        app: tenant-container-{{CHANNEL}}
        group: tenant-containers
        logging: my_group
    spec:
      containers:
      - name: tenant-container-{{CHANNEL}}
        image: {{IMAGE}}
        imagePullPolicy: {{IMAGE_PULL_POLICY}}
        env:
        - name: TWITCH_CHANNEL
          value: "{{CHANNEL}}"
        - name: TWITCH_BOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWITCH_BOT_USERNAME
        - name: TWITCH_BOT_OAUTH_TOKEN
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWITCH_BOT_OAUTH_TOKEN
        - name: BASE_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: BASE_URL
        - name: TWITCH_SUPER_ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWITCH_SUPER_ADMIN_USERNAME
        - name: TWITCH_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWITCH_CLIENT_ID
        - name: TWITCH_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: TWITCH_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: SESSION_SECRET
        - name: STATE_DB_URL
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STATE_DB_URL
        - name: STATE_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: STATE_DB_PASSWORD
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: multibot
  name: tenant-container-{{CHANNEL}}-svc
spec:
  selector:
    app: tenant-container-{{CHANNEL}}
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 80
  type: ClusterIP